server:
  port: 8090

spring:
  datasource:
    name: ibookingdb
    url: jdbc:h2:mem:ibookingdb
    username: sa
    password: test123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver


  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
      encoding: UTF-8

logging:
  level:
    com.huawei.ibooking: debug